# Generated by Django 5.2 on 2025-04-18 08:17

import django.db.models.deletion
import functools
import random
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=functools.partial(random.Random.randrange, *(4, 11), **{}))),
                ('is_available', models.BooleanField()),
            ],
            options={
                'indexes': [models.Index(fields=['seats'], name='bookings_ta_seats_c4bbeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.table')),
            ],
            options={
                'indexes': [models.Index(fields=['table_id'], name='bookings_re_table_i_92392b_idx')],
            },
        ),
    ]
