# Generated by Django 5.2 on 2025-04-18 12:35

import functools
import random
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(default=functools.partial(random.Random.randrange, *(4, 11), **{})),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user_id'], name='bookings_re_user_id_9fa8d8_idx'),
        ),
    ]
